import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Company, PrismaClient } from "@prisma/client";
import { ReactChild, ReactFragment, ReactPortal } from 'react';



const prisma = new PrismaClient();
const Home: NextPage<Company[]> = (companies) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{companies.map((company: Company)=> {
  return (
    <div>
      <h1>{company.name}</h1>
      <p>{company.adress}</p>
    </div>
  )
})}



    </div>
  )
}

export async function getServerSideProps() {

  const companies = await prisma.company.findMany();
  console.log(companies);
  return {
    props: {companies}, 
  }
}

export default Home
